apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: conversao-temperatura
  namespace: conversao-temperatura
spec:
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: conversao-temperatura
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50